# Generated by Django 5.1.6 on 2025-02-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='post',
            name='additional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر'),
        ),
    ]
