# Generated by Django 5.1.6 on 2025-02-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_additional_image_post_additional_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AlterField(
            model_name='post',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر دوم (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='additional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر سوم (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='تصویر اول'),
        ),
    ]
