# Generated by Django 5.1.1 on 2024-09-12 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='آدرس')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(upload_to='Images', verbose_name='تصویر')),
                ('published', models.BooleanField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
            ],
        ),
    ]
