# Generated by Django 5.1.6 on 2025-02-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('message', models.TextField(max_length=2000, verbose_name='متن توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(max_length=2000, verbose_name='پاسخ ادمین')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='آیا خوانده شده ؟')),
            ],
        ),
    ]
