# Generated by Django 5.1.6 on 2025-02-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'لیست پیام ها', 'verbose_name_plural': 'لیست پیام ها'},
        ),
    ]
